version: '3.8'
services:
  futuresbot:
    build: .
    environment:
      - TELEGRAM_TOKEN=8038741822:AAGWnN0s24X8YK9fzd8DiNLz781ZWkdu-oM
      - CHAT_ID=379291385
    volumes:
      - ./models:/app/models
      - ./market_data:/app/market_data
    restart: always
