version: '3.9'

services:
  telegram-futures-bot:
    build: .
    container_name: telegram_futures_bot
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_TOKEN=8038741822:AAGWnN0s24X8YK9fzd8DiNLz781ZWkdu-oM
      - CHAT_ID=379291385
