version: '3.8'
services:
  futuresbot:
    build: .
    environment:
      - TELEGRAM_TOKEN=7982722364:AAF-G_vgZJXv2L-f6KJSxo1h3xd1wuMgrww
      - CHAT_ID=379291385
    volumes:
      - ./models:/app/models
      - ./market_data:/app/market_data
    restart: always
